$reply[$messageID;no]
$title[1;Splash]
$image[1;$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.splash]==null];true;https://discord.com/servers/$getObjectProperty[guild.id]];false;https://cdn.discordapp.com/splashes/$getObjectProperty[guild.id]/$getObjectProperty[guild.splash].$replaceText[$replaceText[$checkContains[$getObjectProperty[guild.splash];a_];true;gif];false;png]?size=2048&quality=lossless]]
$color[1;a09fff]
$title[2;Banner]
$image[2;$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.banner]==null];true;https://discord.com/servers/$getObjectProperty[guild.id]];false;https://cdn.discordapp.com/banners/$getObjectProperty[guild.id]/$getObjectProperty[guild.banner].$replaceText[$replaceText[$checkContains[$getObjectProperty[guild.banner];a_];true;gif];false;png]?size=2048&quality=lossless]]
$color[2;a09fff]
$thumbnail[3;$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.icon]==null];true;$userAvatar[$clientID]];false;https://cdn.discordapp.com/icons/$getObjectProperty[guild.id]/$getObjectProperty[guild.icon].$replaceText[$replaceText[$checkContains[$getObjectProperty[guild.icon];a_];true;gif];false;png]?size=2048&quality=lossless]]
$author[3;$getObjectProperty[code]]
$title[3;$getObjectProperty[guild.name];https://discord.com/invite/$getObjectProperty[code]]
$addField[3;Channel Invite;\`$replaceText[$replaceText[$checkCondition[$getObjectProperty[channel.id]==undefined];true;Vanity];false;#$getObjectProperty[channel.name]
($getObjectProperty[channel.id])]\`;yes]
$addField[3;Boosts;\`$getObjectProperty[guild.premium_subscription_count]\` - \`$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.premium_subscription_count]<2];true;0];false;$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.premium_subscription_count]<7];true;1];false;$replaceText[$replaceText[$checkCondition[$getObjectProperty[guild.premium_subscription_count]<14];true;2];false;3]]] Levels\`;yes]
$addField[3;Inviter Avatar;$replaceText[$replaceText[$checkCondition[$getObjectProperty[inviter.id]==undefined];true;\`Vanity\`];false;[$userTag[$replaceText[$getObjectProperty[inviter.id];undefined;$authorID]]](https://cdn.discordapp.com/avatars/$getObjectProperty[inviter.id]/$getObjectProperty[inviter.avatar].$replaceText[$replaceText[$checkContains[$getObjectProperty[inviter.avatar];a_];true;gif];false;png]?size=2048&quality=lossless)];yes]
$addField[3;Inviter Username;\`$replaceText[$replaceText[$checkCondition[$getObjectProperty[inviter.id]==undefined];true;Vanity];false;$userTag[$replaceText[$getObjectProperty[inviter.id];undefined;$authorID]]]\`;yes]
$addField[3;Inviter ID;\`$replaceText[$replaceText[$checkCondition[$getObjectProperty[inviter.id]==undefined];true;Vanity];false;$getObjectProperty[inviter.id]]\`;yes]
$addField[3;Description;\`$getObjectProperty[guild.description]\`;no]
$addField[3;ID;\`$getObjectProperty[guild.id]\`;no]
$footer[3;$replaceText[$replaceText[$checkCondition[$getObjectProperty[expires_at]==null];true;Always];false;$getObjectProperty[expires_at]]]
$color[3;6f7af5]
$onlyIf[$getObjectProperty[message]!=Unknown Invite;Not Found]
$createObject[$jsonRequest[https://discord.com/api/v9/invites/$replaceText[$replaceText[$replaceText[$message;https://;];discord.gg/;];discord.com/invite/;];;Not Found]]
$argsCheck[>0;Invite ID/URL]
$suppressErrors
